;-----------------------------------------------
; Sound related constants:
; instrument codes are the indexes of their first byte in the profile
MUSIC_INSTRUMENT_SQUARE_WAVE:  equ 0
MUSIC_INSTRUMENT_PIANO:  equ 1
MUSIC_INSTRUMENT_PAD:  equ 15


SFX_PRIORITY_MUSIC:				equ 1	; this is the lowest priority
SFX_PRIORITY_LOW:				equ 2
SFX_PRIORITY_HIGH:				equ 3

MUSIC_CMD_FLAG:					equ #80
MUSIC_CMD_TIME_STEP_FLAG:		equ #40

MUSIC_CMD_SKIP:  equ 0+MUSIC_CMD_FLAG
MUSIC_CMD_SET_INSTRUMENT:  equ 1+MUSIC_CMD_FLAG
MUSIC_CMD_PLAY_INSTRUMENT_CH1:  equ 2+MUSIC_CMD_FLAG
MUSIC_CMD_PLAY_INSTRUMENT_CH2:  equ 3+MUSIC_CMD_FLAG
MUSIC_CMD_PLAY_INSTRUMENT_CH3:  equ 4+MUSIC_CMD_FLAG
MUSIC_CMD_GOTO:  equ 5+MUSIC_CMD_FLAG
MUSIC_CMD_REPEAT:  equ 6+MUSIC_CMD_FLAG
MUSIC_CMD_END_REPEAT:  equ 7+MUSIC_CMD_FLAG
MUSIC_CMD_END:  equ 8+MUSIC_CMD_FLAG
SFX_CMD_END:  equ 9+MUSIC_CMD_FLAG
