; Original source code: https://github.com/AugustoRuiz/WYZTracker
; Converted to Zilog z80 notation by Santiago Ontañón with https://github.com/santiontanon/mdlz80optimizer

; MSX PSG proPLAYER V 0.47c - WYZ 19.03.2016
; (WYZTracker 2.0 o superior)

; RAM
;____________________________________


INTERR:
    org $ + 1  ;INTERRUPTORES 1=ON 0=OFF
;BIT 0=CARGA CANCION ON/OFF
;BIT 1=PLAYER ON/OFF
;BIT 2=EFECTOS ON/OFF
;BIT 3=SFX ON/OFF
;BIT 4=LOOP

;MUSICA **** EL ORDEN DE LAS VARIABLES ES FIJO ******



; SONG:
;     org $ + 1  ;DBNº DE CANCION
TEMPO:
    org $ + 1  ;DB TEMPO
TTEMPO:
    org $ + 1  ;DB CONTADOR TEMPO

PUNTERO_A:
    org $ + 2  ;DW PUNTERO DEL CANAL A
PUNTERO_B:
    org $ + 2  ;DW PUNTERO DEL CANAL B
PUNTERO_C:
    org $ + 2  ;DW PUNTERO DEL CANAL C

CANAL_A:
    org $ + 2  ;DW DIRECION DE INICIO DE LA MUSICA A
CANAL_B:
    org $ + 2  ;DW DIRECION DE INICIO DE LA MUSICA B
CANAL_C:
    org $ + 2  ;DW DIRECION DE INICIO DE LA MUSICA C

PUNTERO_P_A:
    org $ + 2  ;DW PUNTERO PAUTA CANAL A
PUNTERO_P_B:
    org $ + 2  ;DW PUNTERO PAUTA CANAL B
PUNTERO_P_C:
    org $ + 2  ;DW PUNTERO PAUTA CANAL C

PUNTERO_P_A0:
    org $ + 2  ;DW INI PUNTERO PAUTA CANAL A
PUNTERO_P_B0:
    org $ + 2  ;DW INI PUNTERO PAUTA CANAL B
PUNTERO_P_C0:
    org $ + 2  ;DW INI PUNTERO PAUTA CANAL C

PUNTERO_P_DECA:
    org $ + 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL A
PUNTERO_P_DECB:
    org $ + 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL B
PUNTERO_P_DECC:
    org $ + 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL C

PUNTERO_DECA:
    org $ + 2  ;DW PUNTERO DECODER CANAL A
PUNTERO_DECB:
    org $ + 2  ;DW PUNTERO DECODER CANAL B
PUNTERO_DECC:
    org $ + 2  ;DW PUNTERO DECODER CANAL C

REG_NOTA_A:
    org $ + 1  ;DB REGISTRO DE LA NOTA EN EL CANAL A
VOL_INST_A:
    org $ + 1  ;DB VOLUMEN RELATIVO DEL INSTRUMENTO DEL CANAL A
REG_NOTA_B:
    org $ + 1  ;DB REGISTRO DE LA NOTA EN EL CANAL B
VOL_INST_B:
    org $ + 1  ;DB VOLUMEN RELATIVO DEL INSTRUMENTO DEL CANAL B
REG_NOTA_C:
    org $ + 1  ;DB REGISTRO DE LA NOTA EN EL CANAL C
VOL_INST_C:
    org $ + 1  ;DB VOLUMEN RELATIVO DEL INSTRUMENTO DEL CANAL C

PUNTERO_L_DECA:
    org $ + 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL A
PUNTERO_L_DECB:
    org $ + 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL B
PUNTERO_L_DECC:
    org $ + 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL C

;CANAL DE EFECTOS DE RITMO - ENMASCARA OTRO CANAL

PUNTERO_P:
    org $ + 2  ;DW PUNTERO DEL CANAL EFECTOS
CANAL_P:
    org $ + 2  ;DW DIRECION DE INICIO DE LOS EFECTOS
PUNTERO_P_DECP:
    org $ + 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL P
PUNTERO_DECP:
    org $ + 2  ;DW PUNTERO DECODER CANAL P
PUNTERO_L_DECP:
    org $ + 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL P
;SELECT_CANAL_P	DB	INTERR+$36	;DB SELECCION DE CANAL DE EFECTOS DE RITMO


SFX_L:
    org $ + 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO BAJO
SFX_H:
    org $ + 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO ALTO
SFX_V:
    org $ + 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO VOLUMEN
SFX_MIX:
    org $ + 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO MIXER


;EFECTOS DE SONIDO

N_SONIDO:
    org $ + 1  ;DB : NUMERO DE SONIDO
PUNTERO_SONIDO:
    org $ + 2  ;DW : PUNTERO DEL SONIDO QUE SE REPRODUCE



;DB [13] BUFFERs DE REGISTROS DEL PSG

PSG_REG:
    org $ + 16
PSG_REG_SEC:
    org $ + 16
ENVOLVENTE:
    org $ + 1  ;DB : FORMA DE LA ENVOLVENTE
;BIT 0	  : FRECUENCIA CANAL ON/OFF
;BIT 1-2  : RATIO
;BIT 3-3  : FORMA
ENVOLVENTE_BACK:
    org $ + 1  ;DB:	BACKUP DE LA FORMA DE LA ENVOLENTE


;MEMORIA PARA BUFFER DE SONIDO!
;RECOMENDABLE $10 O MAS BYTES POR CANAL.

BUFFER_CANAL_A:
    org $ + #10
BUFFER_CANAL_B:
    org $ + #10
BUFFER_CANAL_C:
    org $ + #10
BUFFER_CANAL_P:
    org $ + #10
