    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

; dialogue state:
dialogue_goto_state:                ds virtual 1
dialogue_n_options:                 ds virtual 1
dialogue_option_target_states:      ds virtual MAX_DIALOGUE_OPTIONS
dialogue_option_text_ids:           ds virtual 2*MAX_DIALOGUE_OPTIONS
dialogue_option_extended_text_ids:  ds virtual 2*MAX_DIALOGUE_OPTIONS

IF IS_6128 == 1
dialogue_buffer:                    ds virtual MAX_DIALOGUE_SIZE
ENDIF

RAMBlock_end:
