    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

; General variables:
interrupt_count:                    ds virtual 1
vsyncs_since_last_frame:            ds virtual 1
game_cycle:                         ds virtual 1
IF IS_6128 == 1
current_4000_page:                  ds virtual 1
ENDIF

IF SCRIPT_CUSTOM_ASSEMBLER_ROOM_DRAW_USED == 1
custom_assembler_room_draw:         ds virtual 2
custom_assembler_room_draw_fullredraw_only: ds virtual 1
ENDIF

IF SCRIPT_CUSTOM_ASSEMBLER_ON_UPDATE_USED == 1
custom_assembler_on_update:         ds virtual 2
ENDIF

current_palette_ptr:                ds virtual 2
last_room_object_ptr:               ds virtual 2  ; contains a pointer to the last object in the room 
                                                  ; (this is just so we don't need to calculate it every frame)

IF PLAYER_SCALING = 1
player_zoom_draw_function_ptr:      ds virtual 2
ENDIF

last_script_in_this_rule:           ds virtual 1

RAMBlock_end:
