    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

; inventory data:
inventory_name_ptrs:                ds virtual INVENTORY_SIZE * 2
inventory_name_buffer:              ds virtual INVENTORY_NAME_BUFFER_SIZE
inventory_name_next_ptr:            ds virtual 2  ; Starts pointing at (inventory_name_buffer) and each time
                                                  ; an item is added, it points to the position after it,
                                                  ; so that we accumulate all the names there.
    
RAMBlock_end:
