    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

MUSIC_current_song:                 ds virtual 1  ; 0 if no song, song offset + 1 if a song is playing
MUSIC_tempo:                        ds virtual 1  ; must be after "MUSIC_current_song", or save/load game would not work
MUSIC_muted:                        ds virtual 1  ; This is different from "MUSIC_tempo == 0", since we need to track when a music should be playing, but we just have it muted.

IF MUSIC_TYPE_TSV == 1

; sound variables:
beginning_of_sound_variables_except_tempo:
MUSIC_tempo_counter:                ds virtual 1
MUSIC_instruments:                  ds virtual 3
MUSIC_channel3_instrument_buffer:   ds virtual 1  ; this stores the instrument of channel 3, which is special, since SFX might overwrite it
MUSIC_start_pointer:                ds virtual 2  
SFX_pointer:                        ds virtual 2
MUSIC_pointer:                      ds virtual 2
MUSIC_repeat_stack_ptr:             ds virtual 2  ; 15
MUSIC_repeat_stack:                 ds virtual 4*3  ; 27
MUSIC_instrument_envelope_ptr:      ds virtual 3*2  ; 33
SFX_priority:                       ds virtual 1  ; the SFX from the game have more priority than those triggered by music
; MUSIC_transpose:                    ds virtual 1
MUSIC_time_step_required:           ds virtual 1  ; 39
load_new_song_request:              ds virtual 2
IF MUSIC_USE_INSTRUMENT_SPEED = 1
MUSIC_instrument_speed:             ds virtual 3
MUSIC_instrument_speed_counter:     ds virtual 3
ENDIF
IF MUSIC_USE_SET_VOLUME = 1
MUSIC_volumes:                      ds virtual 3
ENDIF
end_of_sound_variables:
ENDIF

IF MUSIC_TYPE_WYZ == 1
INTERR:
    ds virtual 1  ;INTERRUPTORES 1=ON 0=OFF
;BIT 0=CARGA CANCION ON/OFF
;BIT 1=PLAYER ON/OFF
;BIT 2=EFECTOS ON/OFF
;BIT 3=SFX ON/OFF
;BIT 4=LOOP

;MUSICA **** EL ORDEN DE LAS VARIABLES ES FIJO ******



; SONG:
;     ds virtual 1  ;DBNº DE CANCION
TEMPO:
    ds virtual 1  ;DB TEMPO
TTEMPO:
    ds virtual 1  ;DB CONTADOR TEMPO

PUNTERO_A:
    ds virtual 2  ;DW PUNTERO DEL CANAL A
PUNTERO_B:
    ds virtual 2  ;DW PUNTERO DEL CANAL B
PUNTERO_C:
    ds virtual 2  ;DW PUNTERO DEL CANAL C

CANAL_A:
    ds virtual 2  ;DW DIRECION DE INICIO DE LA MUSICA A
CANAL_B:
    ds virtual 2  ;DW DIRECION DE INICIO DE LA MUSICA B
CANAL_C:
    ds virtual 2  ;DW DIRECION DE INICIO DE LA MUSICA C

PUNTERO_P_A:
    ds virtual 2  ;DW PUNTERO PAUTA CANAL A
PUNTERO_P_B:
    ds virtual 2  ;DW PUNTERO PAUTA CANAL B
PUNTERO_P_C:
    ds virtual 2  ;DW PUNTERO PAUTA CANAL C

PUNTERO_P_A0:
    ds virtual 2  ;DW INI PUNTERO PAUTA CANAL A
PUNTERO_P_B0:
    ds virtual 2  ;DW INI PUNTERO PAUTA CANAL B
PUNTERO_P_C0:
    ds virtual 2  ;DW INI PUNTERO PAUTA CANAL C

PUNTERO_P_DECA:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL A
PUNTERO_P_DECB:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL B
PUNTERO_P_DECC:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL C

PUNTERO_DECA:
    ds virtual 2  ;DW PUNTERO DECODER CANAL A
PUNTERO_DECB:
    ds virtual 2  ;DW PUNTERO DECODER CANAL B
PUNTERO_DECC:
    ds virtual 2  ;DW PUNTERO DECODER CANAL C

REG_NOTA_A:
    ds virtual 1  ;DB REGISTRO DE LA NOTA EN EL CANAL A
VOL_INST_A:
    ds virtual 1  ;DB VOLUMEN RELATIVO DEL INSTRUMENTO DEL CANAL A
REG_NOTA_B:
    ds virtual 1  ;DB REGISTRO DE LA NOTA EN EL CANAL B
VOL_INST_B:
    ds virtual 1  ;DB VOLUMEN RELATIVO DEL INSTRUMENTO DEL CANAL B
REG_NOTA_C:
    ds virtual 1  ;DB REGISTRO DE LA NOTA EN EL CANAL C
VOL_INST_C:
    ds virtual 1  ;DB VOLUMEN RELATIVO DEL INSTRUMENTO DEL CANAL C

PUNTERO_L_DECA:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL A
PUNTERO_L_DECB:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL B
PUNTERO_L_DECC:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL C

;CANAL DE EFECTOS DE RITMO - ENMASCARA OTRO CANAL

PUNTERO_P:
    ds virtual 2  ;DW PUNTERO DEL CANAL EFECTOS
CANAL_P:
    ds virtual 2  ;DW DIRECION DE INICIO DE LOS EFECTOS
PUNTERO_P_DECP:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL DECODER CANAL P
PUNTERO_DECP:
    ds virtual 2  ;DW PUNTERO DECODER CANAL P
PUNTERO_L_DECP:
    ds virtual 2  ;DW PUNTERO DE INICIO DEL LOOP DEL DECODER CANAL P
;SELECT_CANAL_P	DB	INTERR+$36	;DB SELECCION DE CANAL DE EFECTOS DE RITMO


SFX_L:
    ds virtual 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO BAJO
SFX_H:
    ds virtual 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO ALTO
SFX_V:
    ds virtual 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO VOLUMEN
SFX_MIX:
    ds virtual 2  ;DW DIRECCION BUFFER EFECTOS DE RITMO REGISTRO MIXER


;EFECTOS DE SONIDO

N_SONIDO:
    ds virtual 1  ;DB : NUMERO DE SONIDO
PUNTERO_SONIDO:
    ds virtual 2  ;DW : PUNTERO DEL SONIDO QUE SE REPRODUCE



;DB [13] BUFFERs DE REGISTROS DEL PSG

PSG_REG:
    ds virtual 16
PSG_REG_SEC:
    ds virtual 16
ENVOLVENTE:
    ds virtual 1  ;DB : FORMA DE LA ENVOLVENTE
;BIT 0	  : FRECUENCIA CANAL ON/OFF
;BIT 1-2  : RATIO
;BIT 3-3  : FORMA
ENVOLVENTE_BACK:
    ds virtual 1  ;DB:	BACKUP DE LA FORMA DE LA ENVOLENTE


;MEMORIA PARA BUFFER DE SONIDO!
;RECOMENDABLE $10 O MAS BYTES POR CANAL.

BUFFER_CANAL_A:
    ds virtual #10
BUFFER_CANAL_B:
    ds virtual #10
BUFFER_CANAL_C:
    ds virtual #10
BUFFER_CANAL_P:
    ds virtual #10


; SFX player variables (PSG registers that overwrite those set by the wyz player):
; - registers 2, 3, 6, 7 and 9
SFX_player_registers:   ds virtual 5
SFX_player_active: ds virtual 1
SFX_player_pointer: ds virtual 2

ENDIF
    
RAMBlock_end:
