    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

; Other variables used at different points during execution (some overloaded):
current_column_x:                                 ; used during room drawing
next_tile_idx:                                    ; used during room tile loading
object_type_data_buffer_next_ptr:   ds virtual 2  ; used during room object loading
currently_decompressed_tile_bank:                 ; used during room tile loading
object_type_loaded_cache_next_ptr:  ds virtual 2  ; used during room object loading
room_object_name_buffer_next_ptr:   ds virtual 2  ; used during room object loading
; scrolled_at_least_once:             ds virtual 1  ; whether we have scrolled at least once since the last time 
;                                                   ; "clear_text_area_for_scroll" was called 
text_scrolling_next_row:            ds virtual 1  ; The row at which the new line will be drawn. If this is N_REGULAR_TEXT_ROWS+1, then 
                                                  ; the text will scroll up first
IF DOUBLE_CLICK_ON_EXIT == 1
double_click:                       ds virtual 1
time_since_last_space_click:        ds virtual 1
ENDIF

IF CAN_TURN_GUI_ON_OFF == 1
gui_on:                             ds virtual 1
ENDIF

RAMBlock_end:
