    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

IF USE_PATH_FINDING != 0
; path finding path: initialized to #ff. Each element is a 2 byte (x,y) 
; point. (#ff, #ff) indicates the end of the path. The final destination is not
; part of the path. Once there are no more points in this path, the player will
; go in a straight line towards the target.
path_finding_path_buffer:           ds virtual PATH_FINDING_MAX_LENGTH*2
path_finding_path_ptr:              ds virtual 2
path_finding_stack:                 ds virtual 2
ENDIF
IF USE_PATH_FINDING == 2
path_finding_invoked:               ds virtual 1
ENDIF

RAMBlock_end:
