    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

dirty_column_buffer:                ds virtual MAX_ROOM_WIDTH*4+1   ; we add 1, since sometimes we overflow
column_draw_buffer:                 ds virtual COLUMN_DRAW_BUFFER_SIZE
dirty_min_y:                        ds virtual 1  ; when an object animation is played, it will fill this, to draw more rows than just what the player occupies
dirty_max_y:                        ds virtual 1

RAMBlock_end:
