    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

; This buffer contains first all the object types, and then all the tiles of the
; current room:
tiles_and_object_type_data_buffer:            ds virtual ROOM_TILES_OBJECT_COMBINED_BUFFER_SIZE
; This contains the pointer within 'tiles_and_object_type_data_buffer' where
; the tile data starts:
tile_buffer_ptr:    ds virtual 2

RAMBlock_end:
