    include "constants-autogenerated.asm"
    org #0000

RAMBlock_start:

data_to_zero_on_game_start_start:
keyboard_line_state:                ds virtual 6
keyboard_line_state_prev:           ds virtual 6
keyboard_line_clicks:               ds virtual 6

pointer_x:                          ds virtual 1
pointer_y:                          ds virtual 1
current_pointer_type:               ds virtual 1
pointer_background_buffer_video_mem_ptr:   ds virtual 2
pointer_background_buffer_x:        ds virtual 1  ; the x coordinate divided by 2 (to have it in bytes)
pointer_background_buffer_y:        ds virtual 1
pointer_background_buffer:          ds virtual POINTER_WIDTH_IN_BYTES*POINTER_HEIGHT
pointer_move_time:                  ds virtual 1  ; for how long have we been moving the pointer, to increase speed
force_update_pointer:               ds virtual 1

currently_selected_verb:            ds virtual 1  ; 0 is no verb, 1: examine, 2: pickup, 3: use, 4: talk
currently_selected_item_to_use:     ds virtual 1  ; 0 is no item, and then it starts in 1
current_action_text_buffer:         ds virtual ACTION_TEXT_BUFFER_SIZE
current_action_text_last_length_in_bytes:   ds virtual 1
current_action_text_id:             ds virtual 1  ; a code to indicate whether we need to redraw the current text or not, bits:
                                                  ; XXYYYYYY: XX = 00 nothing, 01 verb, 10 inventory item, 11 object
                                                  ;           YY = ID of the thing selected

; current action the player is executing:
player_in_room:                     ds virtual 1  ; 0 if the player is not in the room, 1 if it is
player_object_ptr:                  ds virtual 2
player_current_action:              ds virtual 1  ; 0: no action, 1: walking
player_current_action_parameters:   ds virtual 2  ; for walking: target coordinates
player_current_action_target_object:    ds virtual 2  ; pointer to the target object, if any

; current event (used for rule matching):
current_event:                      ds virtual 4  ; event can be at most 3 bytes + the terminating 0
redraw_whole_room_signal:           ds virtual 1  ; if this is != 0, we will redraw the whole room 
                                                  ; (for when an object is picked up, for example)
redraw_inventory_signal:            ds virtual 1
exit_upon_clicking_outside:         ds virtual 1  ; if this is != 0, the game knows that there is a rule that will take you to
                                                  ; another room if clicking outside of the game area. So, it is used to display
                                                  ; the "exit" pointer graphic

; persistent state:
data_for_savegame_start:
current_room:                       ds virtual 1
inventory_ids:                      ds virtual INVENTORY_SIZE
game_state_variables:               ds virtual N_GAME_STATE_VARIABLES
data_for_savegame_end:

IF PLAYER_SCALING = 1
player_scale:                       ds virtual 1  ; #ff 112.5%, 0: 100% scale, 1: 87.5%, 2: 75%
ENDIF

; time playing:
; time_ints:                          ds virtual 1
; time_seconds:                       ds virtual 1
; time_minutes:                       ds virtual 1
; time_hours:                         ds virtual 1
data_to_zero_on_game_start_end:
    
RAMBlock_end:
